export default [
  {
    id: 1,
    requestedTo: "mukesh@coinlock.com",
    memo: "Beetlejuice",
    dueDate: "May 21st 8:31 pm",
    paymentType: "BTC",
    amount: 0.03,
    status: "Tim Burton",
  },

  {
    id: 2,
    requestedTo: "mukesh@coinlock.com",
    memo: "Beetlejuice",
    dueDate: "May 21st 8:31 pm",
    paymentType: "BTC",
    amount: 0.03,
    status: "Tim Burton",
  },
  {
    id: 3,
    requestedTo: "mukesh@coinlock.com",
    memo: "Beetlejuice",
    dueDate: "May 21st 8:31 pm",
    paymentType: "BTC",
    amount: 0.03,
    status: "Tim Burton",
  },
  {
    id: 4,
    requestedTo: "mukesh@coinlock.com",
    memo: "Beetlejuice",
    dueDate: "May 21st 8:31 pm",
    paymentType: "BTC",
    amount: 0.03,
    status: "Tim Burton",
  },
  {
    id: 5,
    requestedTo: "mukesh@coinlock.com",
    memo: "Beetlejuice",
    dueDate: "May 21st 8:31 pm",
    paymentType: "BTC",
    amount: 0.03,
    status: "Tim Burton",
  },
];
